name: build-report
run-name: ${{ github.actor }} is building a report
on: [push]
jobs:
  build-report:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Github Action for Typst
        uses: lvignoli/typst-action@v0.1
        with:
          source_file: reports/main.typ
      - name: Archive pdf
        uses: actions/upload-artifact@v4
        with:
          name: report-pdf
          path: |
            main.pdf
            reports/main.pdf

